# Generated by Django 3.2.7 on 2021-09-05 10:48

import applications.wallets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_key', applications.wallets.models.WalletSecretField(max_length=250, verbose_name='private_key')),
                ('address', models.CharField(max_length=42, verbose_name='address')),
                ('currency', models.CharField(choices=[('eth', 'etherium')], default='eth', max_length=3, verbose_name='currency')),
            ],
            options={
                'verbose_name': 'wallet',
                'verbose_name_plural': 'wallets',
                'ordering': ('-id',),
                'unique_together': {('address', 'currency')},
            },
        ),
    ]
